### ISSUE TITLE
Typo "langauge"

### ISSUE THREAD

**Issue by ggreif** [tpetricek/Coeffects.Playground#11]
on page https://github.com/coeffects

**Comment by ggreif** [comment]
Will add more as I am reading your interactive essay...

https://github.com/coeffects/coeffects-playground/blob/4ecb10b95aa6aef3a71e88c0b54b665aad002c0f/content/index.html#L341
- "a variables" --> "variables"

**Comment by ggreif** [comment]
yah, these are pesky: https://github.com/coeffects/coeffects-playground/search?utf8=%E2%9C%93&q=langauge

**Comment by tpetricek** [comment]
Fixed, thanks!
